<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="57" started-at="2017-05-25T03:30:21Z" finished-at="2017-05-25T03:30:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="57" started-at="2017-05-25T03:30:21Z" finished-at="2017-05-25T03:30:21Z">
      <class name="com.test.demo.Hello">
        <test-method status="PASS" signature="testmethod1()[pri:0, instance:com.test.demo.Hello@1de2ea4]" name="testmethod1" duration-ms="10" started-at="2017-05-24T23:30:21Z" finished-at="2017-05-24T23:30:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod1 -->
        <test-method status="PASS" signature="testmethod2()[pri:0, instance:com.test.demo.Hello@1de2ea4]" name="testmethod2" duration-ms="3" started-at="2017-05-24T23:30:21Z" finished-at="2017-05-24T23:30:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod2 -->
        <test-method status="FAIL" signature="testmethod3()[pri:0, instance:com.test.demo.Hello@1de2ea4]" name="testmethod3" duration-ms="2" started-at="2017-05-24T23:30:21Z" finished-at="2017-05-24T23:30:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [QTP1] but found [QTP]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [QTP1] but found [QTP]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.test.demo.Hello.testmethod3(Hello.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod3 -->
        <test-method status="PASS" signature="testmethod4()[pri:0, instance:com.test.demo.Hello@1de2ea4]" name="testmethod4" duration-ms="1" started-at="2017-05-24T23:30:21Z" finished-at="2017-05-24T23:30:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod4 -->
        <test-method status="PASS" signature="testmethod5()[pri:0, instance:com.test.demo.Hello@1de2ea4]" name="testmethod5" duration-ms="1" started-at="2017-05-24T23:30:21Z" finished-at="2017-05-24T23:30:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod5 -->
        <test-method status="PASS" signature="testmethod6()[pri:0, instance:com.test.demo.Hello@1de2ea4]" name="testmethod6" duration-ms="2" started-at="2017-05-24T23:30:21Z" finished-at="2017-05-24T23:30:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod6 -->
        <test-method status="PASS" signature="testmethod7()[pri:0, instance:com.test.demo.Hello@1de2ea4]" name="testmethod7" duration-ms="1" started-at="2017-05-24T23:30:21Z" finished-at="2017-05-24T23:30:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testmethod7 -->
      </class> <!-- com.test.demo.Hello -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
